### ISSUE TITLE
Add support for deployer

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#13]
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:28) [classes!/:1.0.0.M1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
Caused by: java.lang.IllegalStateException: The file [/Users/sgibb/workspace/spring/spring-cloud-consul/pom.xml] contains a BUILD-SNAPSHOT version for a non snapshot release in line number [27]

		<spring-cloud-deployer.version>1.0.3.BUILD-SNAPSHOT</spring-cloud-deployer.version>
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater$PomWalker.visitFile(ProjectPomUpdater.java:137) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater$PomWalker.visitFile(ProjectPomUpdater.java:99) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_91]
	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_91]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.processAllPoms(ProjectPomUpdater.java:92) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.updatePoms(ProjectPomUpdater.java:73) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.updateProjectFromSCRelease(ProjectPomUpdater.java:67) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.Releaser.updateProjectFromScRelease(Releaser.java:31) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.spring.SpringReleaser.release(SpringReleaser.java:41) ~[classes!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:34) [classes!/:1.0.0.M1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	... 14 common frames omitted
```

Happens in s-c-consul

**Comment by marcingrzejszczak** [comment]
Yeah cause why should we allow snapshot version in a non-snapshot release?

**Comment by marcingrzejszczak** [comment]
@spencergibb ping? :P

**Comment by spencergibb** [comment]
The releaser doesn't know how to substitute the deployer version.

**Comment by marcingrzejszczak** [comment]
So how should this work? We could add Deployer over here https://github.com/spring-cloud/spring-cloud-release/blob/vDalston.RELEASE/spring-cloud-dependencies/pom.xml and it would automatically get updated. Another thing is to provide a list of properties to ignore.

**Comment by spencergibb** [comment]
Not sure. They other way would to not have these as snapshot before release (which is what I did).

**Comment by marcingrzejszczak** [comment]
You can use the `releaser.fixed-versions` to set a release version. WDYT ?

**Comment by spencergibb** [comment]
Yeah, if that works, I think it would be fine.

**Comment by ryanjbaxter** [comment]
@spencergibb what exactly did u do to work around the error?  I am trying to release consul for sr7

**Comment by spencergibb** [comment]
Manually​changed it first

**Comment by marcingrzejszczak** [comment]
There's info in the docs that there's a list of manually set versions. You were supposed to set the deployer version as a property

**Comment by spencergibb** [comment]
See first bullet here https://github.com/spring-cloud/spring-cloud-release-tools/blob/master/docs/src/main/asciidoc/spring-cloud-release-tools.adoc#project-options
