### ISSUE TITLE
bumping versions fails and uses incorrect version

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-release-tools#18]
1. i executed the releaser to release config for Dalston
2. it got to the docs publishing step and failed bc `target` did not exist (filed an issue about this)
3. i manually created the target dir and reran the releaser
4. skipped everything up until the docs step
5. the docs step completed sucessfully now it wants to bump the versions, but ran into this error

```
=== REVERTING CHANGES & BUMPING VERSION (RELEASE ONLY)===

Press ENTER to go back to snapshots and bump originalVersion by patch 'q' to quit and 's' to skip



2017-04-07 05:01:59.127  INFO 34455 --- [           main] o.s.c.r.internal.git.ProjectGitUpdater   : Reverting last commit
2017-04-07 05:01:59.383  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomUpdater    : Setting version of parent [spring-cloud-config] to [1.3.1.RELEASE] for module [spring-cloud-config-docs]
2017-04-07 05:01:59.385  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     : Applying version / parent / plugin / project changes to the pom [/Users/ryanjbaxter/git-repos/spring-cloud/spring-cloud-config/docs/pom.xml]
2017-04-07 05:01:59.393  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     :     Updating parent org.springframework.cloud:spring-cloud-config
2017-04-07 05:01:59.393  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     :         from version 1.3.0.BUILD-SNAPSHOT to 1.3.1.RELEASE
2017-04-07 05:01:59.397  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomUpdater    : Successfully stored [/Users/ryanjbaxter/git-repos/spring-cloud/spring-cloud-config/docs/pom.xml]
2017-04-07 05:01:59.398  INFO 34455 --- [           main] o.s.c.r.internal.pom.ProjectPomUpdater   : No snapshot versions remained in the pom
2017-04-07 05:01:59.399  WARN 34455 --- [           main] o.s.c.release.internal.pom.PomUpdater    : There is no info on the [org.springframework.cloud:spring-cloud-build] version
2017-04-07 05:01:59.399  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomUpdater    : Setting [spring-cloud-config] version to [1.3.1.RELEASE]
2017-04-07 05:01:59.401  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     : Applying version / parent / plugin / project changes to the pom [/Users/ryanjbaxter/git-repos/spring-cloud/spring-cloud-config/pom.xml]
2017-04-07 05:01:59.403  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     :     Updating project org.springframework.cloud:spring-cloud-config
2017-04-07 05:01:59.404  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     :         from version 1.3.0.BUILD-SNAPSHOT to 1.3.1.RELEASE
2017-04-07 05:01:59.415  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomUpdater    : Successfully stored [/Users/ryanjbaxter/git-repos/spring-cloud/spring-cloud-config/pom.xml]
2017-04-07 05:01:59.416  INFO 34455 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-04-07 05:01:59.423 ERROR 34455 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:28) [classes!/:1.0.0.M1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [spring-cloud-release-tools-spring-1.0.0.M1.jar:1.0.0.M1]
Caused by: java.lang.IllegalStateException: The file [/Users/ryanjbaxter/git-repos/spring-cloud/spring-cloud-config/pom.xml] contains a BUILD-SNAPSHOT version for a non snapshot release in line number [14]

		<version>1.3.1.BUILD-SNAPSHOT</version>
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater$PomWalker.visitFile(ProjectPomUpdater.java:137) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater$PomWalker.visitFile(ProjectPomUpdater.java:99) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_91]
	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_91]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.processAllPoms(ProjectPomUpdater.java:92) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.updatePoms(ProjectPomUpdater.java:73) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.updatePomsForRootVersion(ProjectPomUpdater.java:80) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.project.ProjectBuilder.bumpVersions(ProjectBuilder.java:98) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.Releaser.rollbackReleaseVersion(Releaser.java:60) ~[spring-cloud-release-tools-core-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.spring.SpringReleaser.release(SpringReleaser.java:68) ~[classes!/:1.0.0.M1]
	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:34) [classes!/:1.0.0.M1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	... 14 common frames omitted

2017-04-07 05:01:59.424  INFO 34455 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@579bb367: startup date [Fri Apr 07 05:00:34 EDT 2017]; root of context hierarchy
2017-04-07 05:01:59.425  INFO 34455 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

This seems incorrect
```
2017-04-07 05:01:59.403  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     :     Updating project org.springframework.cloud:spring-cloud-config
2017-04-07 05:01:59.404  INFO 34455 --- [           main] o.s.c.release.internal.pom.PomWriter     :         from version 1.3.0.BUILD-SNAPSHOT to 1.3.1.RELEASE
```
it just released `.1.3.0.RELEASE` reverted back to the snapshots and now should bump the version to `1.3.1.BUILD-SNAPSHOT`, not `1.3.1.RELEASE`

**Comment by spencergibb** [comment]
Happened in spring-cloud-zookeeper as well
