### ISSUE TITLE
Running meta release post release task fails with error

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#191]
```
o.s.batch.core.job.AbstractJob           : Encountered fatal error executing job
16:48:20 
16:48:20 org.springframework.batch.core.JobExecutionException: Flow execution ended unexpectedly
16:48:20 	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:143) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147) [spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
16:48:20 	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) [spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]
16:48:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]
16:48:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
16:48:20 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
16:48:20 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
16:48:20 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
16:48:20 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
16:48:20 	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127) [spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
16:48:20 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) [spring-aop-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
16:48:20 	at com.sun.proxy.$Proxy60.run(Unknown Source) [na:na]
16:48:20 	at releaser.internal.spring.SpringBatchFlowRunner.runJob(SpringBatchFlowRunner.java:410) [releaser-spring-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at releaser.internal.spring.SpringBatchFlowRunner.runReleaseTasks(SpringBatchFlowRunner.java:246) [releaser-spring-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at releaser.internal.spring.DefaultSpringReleaser.runReleaseTasks(DefaultSpringReleaser.java:99) [releaser-spring-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at releaser.internal.spring.DefaultSpringReleaser.release(DefaultSpringReleaser.java:67) [releaser-spring-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at releaser.ReleaserCommandLineRunner.run(ReleaserCommandLineRunner.java:50) [releaser-spring-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
16:48:20 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
16:48:20 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
16:48:20 	at releaser.ReleaserApplication.main(ReleaserApplication.java:38) [classes!/:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]
16:48:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]
16:48:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
16:48:20 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
16:48:20 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [spring-cloud-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
16:48:20 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [spring-cloud-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
16:48:20 Caused by: org.springframework.batch.core.job.flow.FlowExecutionException: Ended flow=release_1583358500730 at state=release_1583358500730.spring-cloud-commons_Flow_1583358500725 with exception
16:48:20 	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:178) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	... 32 common frames omitted
16:48:20 Caused by: java.lang.IllegalArgumentException: No start state was found. You must specify at least one step in a job.
16:48:20 	at org.springframework.batch.core.job.flow.support.SimpleFlow.initializeTransitions(SimpleFlow.java:277) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:140) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.job.flow.support.state.FlowState.handle(FlowState.java:56) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) ~[spring-batch-core-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
16:48:20 	... 34 common frames omitted
16:48:20 
16:48:20 2020-03-04 21:48:20.894  INFO 2889 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=release_1583358500730]] completed with the following parameters: [{}] and the following status: [FAILED] in 32ms
16:48:21 2020-03-04 21:48:20.964  INFO 2889 --- [           main] r.i.s.SpringBatchExecutionResultHandler  : 
16:48:21 
```

**Comment by marcingrzejszczak** [comment]
closed via https://github.com/spring-cloud/spring-cloud-release-tools/commit/731d68ef50e67b48cd88508d61a995352140d54a
