### ISSUE TITLE
Unable to create templates (email/blog/etc) if `target` dir doesn't exist

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#36]
```
=== CREATING TEMPLATES ===

Create email / blog / tweet etc. templates 'q' to quit and 's' to skip





2017-07-06 10:20:56.629  INFO 19862 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-06 10:20:56.642 ERROR 19862 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:28) [classes!/:1.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
Caused by: java.lang.IllegalStateException: java.io.IOException: No such file or directory
	at org.springframework.cloud.release.internal.template.TemplateGenerator.file(TemplateGenerator.java:48) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.template.TemplateGenerator.email(TemplateGenerator.java:32) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.Releaser.createEmail(Releaser.java:98) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.spring.SpringReleaser.lambda$new$8(SpringReleaser.java:63) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.spring.Task.execute(SpringReleaser.java:151) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.spring.SpringReleaser.lambda$null$11(SpringReleaser.java:75) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_91]
	at org.springframework.cloud.release.internal.spring.SpringReleaser.lambda$new$12(SpringReleaser.java:75) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.spring.SpringReleaser.release(SpringReleaser.java:97) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:34) [classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
	... 14 common frames omitted
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_91]
	at java.io.File.createNewFile(File.java:1012) ~[na:1.8.0_91]
	at org.springframework.cloud.release.internal.template.TemplateGenerator.file(TemplateGenerator.java:43) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	... 24 common frames omitted

2017-07-06 10:20:56.645  INFO 19862 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@579bb367: startup date [Thu Jul 06 10:12:45 MDT 2017]; root of context hierarchy
2017-07-06 10:20:56.646  INFO 19862 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

I created `target` and ran option 10 and it worked fine.

**Comment by marcingrzejszczak** [comment]
Pathetic... Sorry about that
