### ISSUE TITLE
Updating Sagan in jenkins releaser fails

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#58]
https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-consul-releaser/6/console

```
22:53:27 === UPDATE SAGAN ===
22:53:27 
22:53:27 Updating Sagan with release info 
22:53:27 
22:53:27 
22:53:27 2017-11-21 22:53:27.508  INFO 27031 --- [           main] o.s.c.r.i.git.GitRepo$JGitFactory        : Passed username and password - will set a custom credentials provider
22:53:27 2017-11-21 22:53:27.514  INFO 27031 --- [           main] o.s.c.r.internal.sagan.SaganUpdater      : Updating Sagan with 
22:53:27 
22:53:27 ReleaseUpdate{groupId='org.springframework.cloud', artifactId='spring-cloud-consul', version='1.2.2.RELEASE', releaseStatus='GENERAL_AVAILABILITY', refDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-consul/{version}/', apiDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-consul/{version}/', repository=null}
22:53:28 2017-11-21 22:53:28.070  INFO 27031 --- [           main] utoConfigurationReportLoggingInitializer : 
22:53:28 
22:53:28 Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
22:53:28 2017-11-21 22:53:28.074 ERROR 27031 --- [           main] o.s.boot.SpringApplication               : Application startup failed
22:53:28 
22:53:28 java.lang.IllegalStateException: Failed to execute CommandLineRunner
22:53:28 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
22:53:28 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
22:53:28 	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
22:53:28 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
22:53:28 	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:32) [classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
22:53:28 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
22:53:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
22:53:28 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
22:53:28 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
22:53:28 Caused by: org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
22:53:28 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:66) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
22:53:28 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
22:53:28 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
22:53:28 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
22:53:28 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590) ~[spring-web-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
22:53:28 	at org.springframework.cloud.release.internal.sagan.RestTemplateSaganClient.updateRelease(RestTemplateSaganClient.java:48) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.sagan.SaganUpdater.updateSagan(SaganUpdater.java:31) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.Releaser.updateSagan(Releaser.java:160) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$static$9(Tasks.java:59) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.spring.Task.execute(Task.java:40) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$null$10(Tasks.java:78) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_144]
22:53:28 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$static$11(Tasks.java:78) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.spring.Task.execute(Task.java:40) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.spring.OptionsProcessor.processOptions(OptionsProcessor.java:39) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.spring.SpringReleaser.release(SpringReleaser.java:60) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:40) [classes!/:1.0.0.BUILD-SNAPSHOT]
22:53:28 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
22:53:28 	... 12 common frames omitted
22:53:28 
22:53:28 2017-11-21 22:53:28.075  INFO 27031 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1ed6993a: startup date [Tue Nov 21 22:45:18 UTC 2017]; root of context hierarchy
22:53:28 2017-11-21 22:53:28.076  INFO 27031 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
22:53:38 Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
22:53:38 Build step 'Execute shell' marked build as failure
22:53:38 ==> Caught signal: terminated
22:53:38     2017/11/21 22:53:38 [INFO] agent: requesting shutdown
22:53:38     2017/11/21 22:53:38 [INFO] consul: shutting down server
22:53:38     2017/11/21 22:53:38 [WARN] serf: Shutdown without a Leave
22:53:38     2017/11/21 22:53:38 [ERR] dns: error starting tcp server: accept tcp 127.0.0.1:8600: use of closed network connection
22:53:38     2017/11/21 22:53:38 [WARN] serf: Shutdown without a Leave
22:53:38     2017/11/21 22:53:38 [INFO] agent: shutdown complete
22:53:38 Recording test results
22:53:39 Finished: FAILURE
```

**Comment by marcingrzejszczak** [comment]
Should be fixed by adding the buildmaster to the sagan users
