### ISSUE TITLE
pom.xml with different groupId causes failure

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#70]
In the case below, group id was
```
	<groupId>com.example</groupId>
```

```
03:29:16 Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
03:29:16 2017-12-02 03:29:16.178 ERROR 12123 --- [           main] o.s.boot.SpringApplication               : Application startup failed
03:29:16 
03:29:16 java.lang.IllegalStateException: Failed to execute CommandLineRunner
03:29:16 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
03:29:16 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
03:29:16 	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
03:29:16 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
03:29:16 	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:32) [classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
03:29:16 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
03:29:16 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
03:29:16 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
03:29:16 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
03:29:16 Caused by: java.lang.IllegalStateException: The file [/opt/jenkins/data/workspace/spring-cloud-contract-releaser/samples/wiremock-undertow-ssl/pom.xml] contains a BUILD-SNAPSHOT version for a non snapshot release in line number [8]
03:29:16 
03:29:16 	<version>2.0.0.BUILD-SNAPSHOT</version>
03:29:16 	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater$PomWalker.visitFile(ProjectPomUpdater.java:140) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater$PomWalker.visitFile(ProjectPomUpdater.java:99) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_144]
03:29:16 	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_144]
03:29:16 	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.processAllPoms(ProjectPomUpdater.java:92) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.updatePoms(ProjectPomUpdater.java:86) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.pom.ProjectPomUpdater.updateProjectFromSCRelease(ProjectPomUpdater.java:79) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.Releaser.updateProjectFromScRelease(Releaser.java:55) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.Releaser.updateProjectFromScRelease(Releaser.java:50) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$static$0(Tasks.java:17) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.spring.Task.execute(Task.java:40) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$null$10(Tasks.java:78) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_144]
03:29:16 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$static$11(Tasks.java:78) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.spring.Task.execute(Task.java:40) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.spring.OptionsProcessor.processOptions(OptionsProcessor.java:39) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.spring.SpringReleaser.release(SpringReleaser.java:60) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:40) [classes!/:1.0.0.BUILD-SNAPSHOT]
03:29:16 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
03:29:16 	... 12 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
That's deliberate and makes perfect sense.

However, every single time it's related to a sample app. So when I do this - https://github.com/spring-cloud/spring-cloud-release-tools/issues/67 - the problem will be gone cause we won't check snapshot versions of these projects.

**Comment by spencergibb** [comment]
For broader adoption that might not always be the case

**Comment by marcingrzejszczak** [comment]
So how can we resolve for which group ids do we upgrade the versions? Or actually for which we check the snapshot versions. For sure the requirement to check only those that are deployable makes sense. Anything else that comes to your mind?
