### ISSUE TITLE
Something's wrong with Sagan update

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-release-tools#75]
```
18:50:39 Updating Sagan with release info 
18:50:39 
18:50:39 
18:50:39 2018-02-08 18:50:39.938  INFO 30155 --- [           main] o.s.c.r.i.git.GitRepo$JGitFactory        : Passed username and password - will set a custom credentials provider
18:50:39 2018-02-08 18:50:39.941  INFO 30155 --- [           main] o.s.c.r.internal.sagan.SaganUpdater      : Version is GA [1.3.2.RELEASE]. Will remove all older versions and mark this as current
18:50:40 2018-02-08 18:50:40.664  INFO 30155 --- [           main] o.s.c.r.internal.sagan.SaganUpdater      : Removing [spring-cloud-sleuth/1.3.2.BUILD-SNAPSHOT] from Sagan
18:50:41 2018-02-08 18:50:41.019  INFO 30155 --- [           main] o.s.c.r.i.sagan.RestTemplateSaganClient  : Response from Sagan
18:50:41 
18:50:41 [<200 OK,Release{releaseStatus='SNAPSHOT', refDocUrl='http://cloud.spring.io/spring-cloud-sleuth/1.3.x/', apiDocUrl='http://cloud.spring.io/spring-cloud-sleuth/1.3.x/', groupId='org.springframework.cloud', artifactId='spring-cloud-sleuth', repository=Repository{id='spring-snapshots', name='Spring Snapshots', url='https://repo.spring.io/libs-snapshot', snapshotsEnabled=true}, version='1.3.2.BUILD-SNAPSHOT', current=false, generalAvailability=false, preRelease=false, versionDisplayName='1.3.2', snapshot=true},{Date=[Thu, 08 Feb 2018 18:50:41 GMT], Content-Type=[application/json;charset=UTF-8], Connection=[keep-alive], Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], Content-Disposition=[inline;filename=f.txt], Expires=[0], Pragma=[no-cache], Strict-Transport-Security=[max-age=31536000], Vary=[Accept-Encoding], X-Application-Context=[sagan-blue:production,cloudfoundry,cloud:0], X-Content-Type-Options=[nosniff], X-Frame-Options=[DENY], X-Vcap-Request-Id=[a858e802-ad07-4d7f-4c10-094553c812b3], X-Xss-Protection=[1; mode=block], Expect-CT=[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"], Server=[cloudflare], CF-RAY=[3ea0c6a48c6d6d00-SJC]}>] 
18:50:41  with body [Release{releaseStatus='SNAPSHOT', refDocUrl='http://cloud.spring.io/spring-cloud-sleuth/1.3.x/', apiDocUrl='http://cloud.spring.io/spring-cloud-sleuth/1.3.x/', groupId='org.springframework.cloud', artifactId='spring-cloud-sleuth', repository=Repository{id='spring-snapshots', name='Spring Snapshots', url='https://repo.spring.io/libs-snapshot', snapshotsEnabled=true}, version='1.3.2.BUILD-SNAPSHOT', current=false, generalAvailability=false, preRelease=false, versionDisplayName='1.3.2', snapshot=true}]
18:50:41 2018-02-08 18:50:41.020  INFO 30155 --- [           main] o.s.c.r.internal.sagan.SaganUpdater      : Removing [spring-cloud-sleuth/1.3.1.RELEASE] from Sagan
18:50:41 2018-02-08 18:50:41.543  INFO 30155 --- [           main] o.s.c.r.i.sagan.RestTemplateSaganClient  : Response from Sagan
18:50:41 
18:50:41 [<200 OK,Release{releaseStatus='GENERAL_AVAILABILITY', refDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.1.RELEASE/', apiDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.1.RELEASE/', groupId='org.springframework.cloud', artifactId='spring-cloud-sleuth', repository=null, version='1.3.1.RELEASE', current=false, generalAvailability=true, preRelease=false, versionDisplayName='1.3.1', snapshot=false},{Date=[Thu, 08 Feb 2018 18:50:41 GMT], Content-Type=[application/json;charset=UTF-8], Connection=[keep-alive], Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], Content-Disposition=[inline;filename=f.txt], Expires=[0], Pragma=[no-cache], Strict-Transport-Security=[max-age=31536000], Vary=[Accept-Encoding], X-Application-Context=[sagan-blue:production,cloudfoundry,cloud:0], X-Content-Type-Options=[nosniff], X-Frame-Options=[DENY], X-Vcap-Request-Id=[305a24a8-6f13-4a57-6f3e-ee7f9a3ebb4d], X-Xss-Protection=[1; mode=block], Expect-CT=[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"], Server=[cloudflare], CF-RAY=[3ea0c6a65d006d00-SJC]}>] 
18:50:41  with body [Release{releaseStatus='GENERAL_AVAILABILITY', refDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.1.RELEASE/', apiDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.1.RELEASE/', groupId='org.springframework.cloud', artifactId='spring-cloud-sleuth', repository=null, version='1.3.1.RELEASE', current=false, generalAvailability=true, preRelease=false, versionDisplayName='1.3.1', snapshot=false}]
18:50:41 2018-02-08 18:50:41.544  INFO 30155 --- [           main] o.s.c.r.internal.sagan.SaganUpdater      : Removing [spring-cloud-sleuth/1.3.0.RELEASE] from Sagan
18:50:41 2018-02-08 18:50:41.920  INFO 30155 --- [           main] o.s.c.r.i.sagan.RestTemplateSaganClient  : Response from Sagan
18:50:41 
18:50:41 [<200 OK,Release{releaseStatus='GENERAL_AVAILABILITY', refDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.0.RELEASE/', apiDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.0.RELEASE/', groupId='org.springframework.cloud', artifactId='spring-cloud-sleuth', repository=null, version='1.3.0.RELEASE', current=false, generalAvailability=true, preRelease=false, versionDisplayName='1.3.0', snapshot=false},{Date=[Thu, 08 Feb 2018 18:50:41 GMT], Content-Type=[application/json;charset=UTF-8], Connection=[keep-alive], Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], Content-Disposition=[inline;filename=f.txt], Expires=[0], Pragma=[no-cache], Strict-Transport-Security=[max-age=31536000], Vary=[Accept-Encoding], X-Application-Context=[sagan-blue:production,cloudfoundry,cloud:0], X-Content-Type-Options=[nosniff], X-Frame-Options=[DENY], X-Vcap-Request-Id=[4dc0e512-ca37-4a62-5212-358803244902], X-Xss-Protection=[1; mode=block], Expect-CT=[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"], Server=[cloudflare], CF-RAY=[3ea0c6a99e196d00-SJC]}>] 
18:50:41  with body [Release{releaseStatus='GENERAL_AVAILABILITY', refDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.0.RELEASE/', apiDocUrl='http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.0.RELEASE/', groupId='org.springframework.cloud', artifactId='spring-cloud-sleuth', repository=null, version='1.3.0.RELEASE', current=false, generalAvailability=true, preRelease=false, versionDisplayName='1.3.0', snapshot=false}]
18:50:41 2018-02-08 18:50:41.921  INFO 30155 --- [           main] o.s.c.r.internal.sagan.SaganUpdater      : Removing [spring-cloud-sleuth/1.3.2.BUILD-SNAPSHOT] from Sagan
18:50:42 2018-02-08 18:50:42.515  WARN 30155 --- [           main] o.s.cloud.release.internal.Releaser      : 
18:50:42 Unable to update Sagan for branch [1.3.x]
18:50:42 
18:50:42 org.springframework.web.client.HttpClientErrorException: 404 Not Found
18:50:42 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:85) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
18:50:42 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
18:50:42 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
18:50:42 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:620) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
18:50:42 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:538) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
18:50:42 	at org.springframework.cloud.release.internal.sagan.RestTemplateSaganClient.deleteRelease(RestTemplateSaganClient.java:43) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.sagan.SaganUpdater.removeVersionFromSagan(SaganUpdater.java:59) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.sagan.SaganUpdater.updateSaganForGa(SaganUpdater.java:41) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.sagan.SaganUpdater.updateSagan(SaganUpdater.java:27) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.Releaser.updateSagan(Releaser.java:171) ~[spring-cloud-release-tools-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$static$10(Tasks.java:65) [classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.spring.Task.execute(Task.java:41) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$null$11(Tasks.java:85) [classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_144]
18:50:42 	at org.springframework.cloud.release.internal.spring.Tasks.lambda$static$12(Tasks.java:85) [classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.spring.Task.execute(Task.java:41) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.spring.OptionsProcessor.processOptions(OptionsProcessor.java:39) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.spring.SpringReleaser.release(SpringReleaser.java:60) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:40) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
18:50:42 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
18:50:42 	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
18:50:42 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
18:50:42 	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:32) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
18:50:42 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
18:50:42 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
18:50:42 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
18:50:42 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
18:50:42 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
18:50:42 
18:50:42 2018-02-08 18:50:42.515  INFO 30155 --- [           main] o.s.cloud.release.internal.spring.Task   : 
18:50:42 
```

THere was no Sleuth `1.3.2.RELEASE` in Sagan

**Comment by marcingrzejszczak** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-release-tools/commit/1e06544cebf446ce328318cd3301c9d1069f5f77
