### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#97]
```
01:11:54 Following exception has occurred: 
01:11:54 null
01:11:54 java.lang.NullPointerException
01:11:54 	at org.springframework.cloud.release.internal.options.Options.removeQuotingChars(Options.java:31)
01:11:54 	at org.springframework.cloud.release.internal.options.Options.<init>(Options.java:27)
01:11:54 	at org.springframework.cloud.release.internal.options.OptionsBuilder.options(OptionsBuilder.java:45)
01:11:54 	at org.springframework.cloud.release.internal.spring.OptionsParser.parse(OptionsParser.java:93)
01:11:54 	at org.springframework.cloud.release.internal.ReleaserApplication.run(ReleaserApplication.java:44)
01:11:54 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
01:11:54 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
01:11:54 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
01:11:54 	at org.springframework.cloud.release.internal.ReleaserApplication.main(ReleaserApplication.java:37)
01:11:54 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:11:54 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:11:54 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:11:54 	at java.lang.reflect.Method.invoke(Method.java:498)
01:11:54 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
01:11:54 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
01:11:54 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
01:11:54 	at 
```

**Comment by spencergibb** [comment]
Closed via ce4569a752669a4f48498058de08c6f0bbfa7303
